import { 
  Code2, FileCode, Container, CheckCircle2, Brain, Cpu, Gem, Terminal, 
  Coffee, Cog, Blocks, FileType, Zap, Smartphone, Globe, FlaskConical, 
  Sparkles, Sigma, Hash, Feather, Moon, Bird, BarChart3, Database,
  LucideIcon
} from "lucide-react";

export interface AgentInfo {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  iconBg: string;
  borderColor: string;
  status: "active" | "idle" | "error";
  tasks: number;
  suggestions: string[];
}

export const agentConfig: Record<string, AgentInfo> = {
  python: {
    id: "python",
    name: "Python Agent",
    description: "Backend services, ML prototypes, API endpoints, and data processing scripts.",
    icon: Code2,
    iconBg: "bg-python/10 text-python",
    borderColor: "border-python/30 hover:border-python/60",
    status: "active",
    tasks: 3,
    suggestions: [
      "Create a REST API with Flask",
      "Build a data pipeline with pandas",
      "Write unit tests with pytest",
      "Create a FastAPI service",
    ],
  },
  javascript: {
    id: "javascript",
    name: "JavaScript Agent",
    description: "Frontend components, Node.js services, React UI, and real-time features.",
    icon: FileCode,
    iconBg: "bg-javascript/10 text-javascript",
    borderColor: "border-javascript/30 hover:border-javascript/60",
    status: "active",
    tasks: 2,
    suggestions: [
      "Create a React component",
      "Build a Node.js API server",
      "Write Jest tests",
      "Create a real-time WebSocket handler",
    ],
  },
  typescript: {
    id: "typescript",
    name: "TypeScript Agent",
    description: "Type-safe applications, enterprise-grade APIs, and strongly-typed libraries.",
    icon: FileType,
    iconBg: "bg-typescript/10 text-typescript",
    borderColor: "border-typescript/30 hover:border-typescript/60",
    status: "active",
    tasks: 4,
    suggestions: [
      "Create typed React components",
      "Build a type-safe API client",
      "Define complex type interfaces",
      "Create a typed state management solution",
    ],
  },
  golang: {
    id: "golang",
    name: "Go Agent",
    description: "High-performance services, microservices, CLI tools, and concurrent systems.",
    icon: Zap,
    iconBg: "bg-golang/10 text-golang",
    borderColor: "border-golang/30 hover:border-golang/60",
    status: "active",
    tasks: 2,
    suggestions: [
      "Build a CLI tool with Cobra",
      "Create a concurrent worker pool",
      "Build a REST API with Gin",
      "Write Go tests with table-driven tests",
    ],
  },
  rust: {
    id: "rust",
    name: "Rust Agent",
    description: "Systems programming, memory-safe code, WebAssembly, and performance-critical apps.",
    icon: Cog,
    iconBg: "bg-rust/10 text-rust",
    borderColor: "border-rust/30 hover:border-rust/60",
    status: "idle",
    tasks: 1,
    suggestions: [
      "Create a CLI with clap",
      "Build a WebAssembly module",
      "Write safe concurrent code",
      "Create a high-performance parser",
    ],
  },
  cpp: {
    id: "cpp",
    name: "C++ Agent",
    description: "Game engines, embedded systems, high-performance computing, and native apps.",
    icon: Cpu,
    iconBg: "bg-cpp/10 text-cpp",
    borderColor: "border-cpp/30 hover:border-cpp/60",
    status: "active",
    tasks: 2,
    suggestions: [
      "Create a game loop",
      "Build a memory-efficient data structure",
      "Write multithreaded code",
      "Create a signal processing algorithm",
    ],
  },
  java: {
    id: "java",
    name: "Java Agent",
    description: "Enterprise applications, Android apps, Spring services, and distributed systems.",
    icon: Coffee,
    iconBg: "bg-java/10 text-java",
    borderColor: "border-java/30 hover:border-java/60",
    status: "idle",
    tasks: 0,
    suggestions: [
      "Create a Spring Boot service",
      "Build an Android Activity",
      "Write JUnit tests",
      "Create a design pattern implementation",
    ],
  },
  bash: {
    id: "bash",
    name: "Bash Agent",
    description: "Shell scripts, automation tasks, system administration, and deployment scripts.",
    icon: Terminal,
    iconBg: "bg-bash/10 text-bash",
    borderColor: "border-bash/30 hover:border-bash/60",
    status: "active",
    tasks: 3,
    suggestions: [
      "Create a deployment script",
      "Build a backup automation",
      "Write a system monitoring script",
      "Create a log analysis tool",
    ],
  },
  ruby: {
    id: "ruby",
    name: "Ruby Agent",
    description: "Rails applications, automation scripts, DSLs, and rapid prototyping.",
    icon: Gem,
    iconBg: "bg-ruby/10 text-ruby",
    borderColor: "border-ruby/30 hover:border-ruby/60",
    status: "idle",
    tasks: 0,
    suggestions: [
      "Create a Rails controller",
      "Build a Ruby gem",
      "Write RSpec tests",
      "Create a Rake task",
    ],
  },
  swift: {
    id: "swift",
    name: "Swift Agent",
    description: "iOS/macOS apps, server-side Swift, and Apple ecosystem development.",
    icon: Blocks,
    iconBg: "bg-swift/10 text-swift",
    borderColor: "border-swift/30 hover:border-swift/60",
    status: "idle",
    tasks: 1,
    suggestions: [
      "Create a SwiftUI view",
      "Build a Combine pipeline",
      "Write an iOS network layer",
      "Create a Core Data model",
    ],
  },
  kotlin: {
    id: "kotlin",
    name: "Kotlin Agent",
    description: "Android development, multiplatform apps, and JVM-based services.",
    icon: Smartphone,
    iconBg: "bg-kotlin/10 text-kotlin",
    borderColor: "border-kotlin/30 hover:border-kotlin/60",
    status: "active",
    tasks: 2,
    suggestions: [
      "Create a Compose UI",
      "Build a coroutine-based service",
      "Write Kotlin multiplatform code",
      "Create a ViewModel with StateFlow",
    ],
  },
  php: {
    id: "php",
    name: "PHP Agent",
    description: "Web applications, Laravel/Symfony backends, and WordPress plugins.",
    icon: Globe,
    iconBg: "bg-php/10 text-php",
    borderColor: "border-php/30 hover:border-php/60",
    status: "idle",
    tasks: 0,
    suggestions: [
      "Create a Laravel controller",
      "Build a WordPress plugin",
      "Write PHPUnit tests",
      "Create a Symfony service",
    ],
  },
  scala: {
    id: "scala",
    name: "Scala Agent",
    description: "Functional programming, Spark applications, and distributed systems.",
    icon: FlaskConical,
    iconBg: "bg-scala/10 text-scala",
    borderColor: "border-scala/30 hover:border-scala/60",
    status: "idle",
    tasks: 1,
    suggestions: [
      "Create a Spark job",
      "Build a functional data pipeline",
      "Write Akka actors",
      "Create a type-safe API with Cats",
    ],
  },
  elixir: {
    id: "elixir",
    name: "Elixir Agent",
    description: "Real-time systems, Phoenix web apps, and fault-tolerant services.",
    icon: Sparkles,
    iconBg: "bg-elixir/10 text-elixir",
    borderColor: "border-elixir/30 hover:border-elixir/60",
    status: "active",
    tasks: 2,
    suggestions: [
      "Create a Phoenix LiveView",
      "Build a GenServer",
      "Write ExUnit tests",
      "Create an Ecto schema",
    ],
  },
  haskell: {
    id: "haskell",
    name: "Haskell Agent",
    description: "Pure functional code, type-safe systems, and compiler development.",
    icon: Sigma,
    iconBg: "bg-haskell/10 text-haskell",
    borderColor: "border-haskell/30 hover:border-haskell/60",
    status: "idle",
    tasks: 0,
    suggestions: [
      "Create a parser with Parsec",
      "Build a monad transformer stack",
      "Write QuickCheck tests",
      "Create a type-level computation",
    ],
  },
  csharp: {
    id: "csharp",
    name: "C# Agent",
    description: ".NET applications, Unity games, and Windows desktop software.",
    icon: Hash,
    iconBg: "bg-csharp/10 text-csharp",
    borderColor: "border-csharp/30 hover:border-csharp/60",
    status: "active",
    tasks: 3,
    suggestions: [
      "Create an ASP.NET controller",
      "Build a Unity game script",
      "Write xUnit tests",
      "Create a LINQ query pipeline",
    ],
  },
  dart: {
    id: "dart",
    name: "Dart Agent",
    description: "Flutter mobile apps, cross-platform UI, and web applications.",
    icon: Feather,
    iconBg: "bg-dart/10 text-dart",
    borderColor: "border-dart/30 hover:border-dart/60",
    status: "active",
    tasks: 4,
    suggestions: [
      "Create a Flutter widget",
      "Build a state management solution",
      "Write Flutter tests",
      "Create a custom painter",
    ],
  },
  lua: {
    id: "lua",
    name: "Lua Agent",
    description: "Game scripting, embedded systems, and configuration scripts.",
    icon: Moon,
    iconBg: "bg-lua/10 text-lua",
    borderColor: "border-lua/30 hover:border-lua/60",
    status: "idle",
    tasks: 0,
    suggestions: [
      "Create a game script",
      "Build a Neovim plugin",
      "Write a Love2D game",
      "Create configuration scripts",
    ],
  },
  perl: {
    id: "perl",
    name: "Perl Agent",
    description: "Text processing, system administration, and legacy integrations.",
    icon: Bird,
    iconBg: "bg-perl/10 text-perl",
    borderColor: "border-perl/30 hover:border-perl/60",
    status: "idle",
    tasks: 0,
    suggestions: [
      "Create a text processing script",
      "Build a regex parser",
      "Write a CGI handler",
      "Create a log analyzer",
    ],
  },
  rlang: {
    id: "rlang",
    name: "R Agent",
    description: "Statistical computing, data analysis, and visualization scripts.",
    icon: BarChart3,
    iconBg: "bg-rlang/10 text-rlang",
    borderColor: "border-rlang/30 hover:border-rlang/60",
    status: "idle",
    tasks: 1,
    suggestions: [
      "Create a ggplot visualization",
      "Build a statistical model",
      "Write a data cleaning pipeline",
      "Create an R Shiny app",
    ],
  },
  sql: {
    id: "sql",
    name: "SQL Agent",
    description: "Database schemas, queries, migrations, and stored procedures.",
    icon: Database,
    iconBg: "bg-sql/10 text-sql",
    borderColor: "border-sql/30 hover:border-sql/60",
    status: "active",
    tasks: 2,
    suggestions: [
      "Create a database schema",
      "Write complex queries with CTEs",
      "Build a migration script",
      "Create stored procedures",
    ],
  },
  devops: {
    id: "devops",
    name: "DevOps Agent",
    description: "CI/CD pipelines, Docker configs, infrastructure manifests, and deployments.",
    icon: Container,
    iconBg: "bg-devops/10 text-devops",
    borderColor: "border-devops/30 hover:border-devops/60",
    status: "active",
    tasks: 2,
    suggestions: [
      "Create a Dockerfile",
      "Build a CI/CD pipeline",
      "Write Kubernetes manifests",
      "Create Terraform configs",
    ],
  },
  verifier: {
    id: "verifier",
    name: "Verifier Agent",
    description: "Automated testing, code validation, security scanning, and quality checks.",
    icon: CheckCircle2,
    iconBg: "bg-verifier/10 text-verifier",
    borderColor: "border-verifier/30 hover:border-verifier/60",
    status: "active",
    tasks: 5,
    suggestions: [
      "Review code for bugs",
      "Create a testing strategy",
      "Write security tests",
      "Generate test coverage report",
    ],
  },
  planner: {
    id: "planner",
    name: "Planner Agent",
    description: "Task orchestration, dependency resolution, resource allocation, and scheduling.",
    icon: Brain,
    iconBg: "bg-planner/10 text-planner",
    borderColor: "border-planner/30 hover:border-planner/60",
    status: "active",
    tasks: 1,
    suggestions: [
      "Break down a project into tasks",
      "Create a development roadmap",
      "Design system architecture",
      "Plan a feature implementation",
    ],
  },
};

export const agentList = Object.values(agentConfig);
